project:
  type: website
  output-dir: docs

website:
  title: "Vitor de Andrade Kamimura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: about.qmd
        text: About
      - href: fieldwork.qmd
        text: Fieldwork
      - href: code.qmd
        text: Code

format:
  html:
    theme: cosmo
