project:
  type: website
  output-dir: docs

website:
  title: "Vitor Kamimura"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: fieldwork.qmd
        text: Fieldwork
      - href: code.qmd
        text: Coding

format:
  html:
    theme: minty
    css: styles.css
    include-in-header: icons.html
    page-layout: full
